
package tbo.soap.tp3;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorldService", targetNamespace = "http://tp3.soap.tbo/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorldService {


    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "helloWorld", targetNamespace = "http://tp3.soap.tbo/", className = "tbo.soap.tp3.HelloWorld")
    @ResponseWrapper(localName = "helloWorldResponse", targetNamespace = "http://tp3.soap.tbo/", className = "tbo.soap.tp3.HelloWorldResponse")
    @Action(input = "http://tp3.soap.tbo/HelloWorldService/helloWorldRequest", output = "http://tp3.soap.tbo/HelloWorldService/helloWorldResponse")
    public String helloWorld(
        @WebParam(name = "name", targetNamespace = "")
        String name);

}
