version: '3.7'
services:
  mongodb:
    build: ./mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: streamingserver
      MONGO_INITDB_ROOT_PASSWORD: wEjjASLg5Jsqjtcv
      MONGO_INITDB_DATABASE: admin

  app:
    build: ./app
    container_name: app
    command: bash /tmp/run.sh
    volumes: 
      - './app:/app'
    ports:
      - "10000:10000"
      - "5000:5000"
    links:
      - mongodb