version: '3.7'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: streamingserver
      MONGO_INITDB_ROOT_PASSWORD: wEjjASLg5Jsqjtcv

  app:
    build: .
    container_name: app
    ports:
      - "10000:10000"
      - "5000:5000"
    links:
      - mongodb