#!/bin/zsh
VERSION='Q7'
OUT_PRODUCTION="./out/production/$VERSION"
OUT_ARTIFACTS="./out/artifacts/$VERSION"
RM_1="rm -rf $OUT_PRODUCTION"
RM_2="rm -rf $OUT_ARTIFACTS"
MKDIR="mkdir $OUT_PRODUCTION $OUT_ARTIFACTS"
eval $RM_1
eval $RM_2
eval $MKDIR
CP_META_INF="cp -r src/META-INF/ $OUT_PRODUCTION/META-INF"
FILES_LIST=`find . -name "*.java"|xargs echo`
JAVAC_COMMAND="javac -d $OUT_PRODUCTION $FILES_LIST"
JAR_COMMAND="jar cvfm $OUT_ARTIFACTS/$VERSION.jar ./src/META-INF/MANIFEST.MF -C $OUT_PRODUCTION/ ."
DEPLOY_COMMAND="asadmin deploy $OUT_ARTIFACTS/$VERSION.jar"
eval $CP_META_INF
eval $JAVAC_COMMAND
eval $JAR_COMMAND
eval $DEPLOY_COMMAND
